const fs = require('fs');
const path = require('path');
const locations = require('../data/locations.json');
const services = require('../data/services.json');
const out = path.join(__dirname, '..', 'dist');
const site = 'https://completeservicesolution.online';
const phone = '9654357541';
const email = 'css.serviceinfo@gmail.com';
const wa = '919654357541';
const company = 'CSS Service Solution';
const states = ['Uttar Pradesh','Bihar','Haryana','Rajasthan','Punjab'];
const stateSlug = {'Uttar Pradesh':'uttar-pradesh','Bihar':'bihar','Haryana':'haryana','Rajasthan':'rajasthan','Punjab':'punjab'};
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug = s => String(s).toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function ensure(d){fs.mkdirSync(d,{recursive:true});}
function write(rel, html){const f=path.join(out,rel); ensure(path.dirname(f)); fs.writeFileSync(f, html);}
function layout(title, description, body, canonical){return `<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><link rel="icon" href="/logo.png"><meta name="theme-color" content="#0756c9"><style>${css}</style></head><body><header><div class="wrap nav"><a class="brand" href="/"><img src="/logo.png" alt="CSS Service Solution logo"><span>CSS Service Solution</span></a><nav><a href="/services/">Services</a><a href="/service-areas/">Service Areas</a><a href="/contact/">Contact</a></nav><a class="call" href="tel:${phone}">Call ${phone}</a></div></header><main>${body}</main><footer><div class="wrap foot"><div><img src="/logo.png" alt="CSS Service Solution" class="flogo"><p><strong>CSS Service Solution</strong></p><p>Professional pest control and termite treatment services.</p></div><div><h3>Contact</h3><p><a href="tel:${phone}">${phone}</a><br><a href="mailto:${email}">${email}</a><br>Service coverage across Uttar Pradesh, Bihar, Haryana, Rajasthan and Punjab.</p></div></div><div class="copy">© ${new Date().getFullYear()} CSS Service Solution. All rights reserved.</div></footer></body></html>`;}
const css=`*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;color:#172033;background:#fff;line-height:1.65}a{color:#0756c9;text-decoration:none}.wrap{max-width:1180px;margin:auto;padding:0 22px}header{position:sticky;top:0;background:#fff;border-bottom:1px solid #e8edf5;z-index:10}.nav{min-height:76px;display:flex;align-items:center;gap:28px}.brand{display:flex;align-items:center;gap:10px;font-weight:800;color:#123}.brand img{width:54px;height:54px;object-fit:contain}.brand span{font-size:19px}nav{display:flex;gap:22px;margin-left:auto}nav a{font-weight:700;color:#25324a}.call,.btn{background:#0756c9;color:#fff;padding:11px 17px;border-radius:8px;font-weight:800}.hero{padding:72px 0;background:linear-gradient(135deg,#f5f9ff,#fff)}.hero h1{font-size:clamp(34px,5vw,58px);line-height:1.08;margin:0 0 18px}.hero p{font-size:20px;max-width:760px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:25px}.btn.secondary{background:#16a34a}.section{padding:55px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}.card{border:1px solid #e4e9f2;border-radius:14px;padding:22px;background:#fff;box-shadow:0 6px 20px rgba(20,50,100,.05)}.card h3{margin-top:0}.crumb{font-size:14px;color:#637089;margin-bottom:20px}.notice{padding:18px;border-left:4px solid #0756c9;background:#f4f8ff;border-radius:8px}.form{display:grid;gap:12px;max-width:650px}.form input,.form select,.form textarea{width:100%;padding:13px;border:1px solid #ccd5e4;border-radius:8px;font:inherit}.form textarea{min-height:130px}.foot{padding:45px 22px;display:grid;grid-template-columns:1fr 1fr;gap:30px}.flogo{width:80px;height:80px;object-fit:contain}.copy{text-align:center;border-top:1px solid #e8edf5;padding:18px;color:#68748b;font-size:14px}ul{padding-left:22px}@media(max-width:760px){nav{display:none}.nav{gap:10px}.call{margin-left:auto;font-size:13px}.foot{grid-template-columns:1fr}.hero{padding:48px 0}}`;
function serviceCards(){return services.map(s=>`<article class="card"><h3><a href="/services/${s.slug}/">${esc(s.name)}</a></h3><p>${esc(s.desc)}</p></article>`).join('');}
function locationCards(list){return list.map(l=>`<article class="card"><h3><a href="/${l.state_slug}/${l.slug}/">${esc(l.branch)}</a></h3><p>${esc(l.state)}</p><p>${l.addresses.length} address${l.addresses.length===1?'':'es'} on file.</p></article>`).join('');}
function faq(city){return `<h2>Frequently Asked Questions</h2><div class="grid"><article class="card"><h3>Do you provide pest control in ${esc(city)}?</h3><p>CSS Service Solution lists service coverage for ${esc(city)}. Contact us to confirm the service, property type and appointment availability.</p></article><article class="card"><h3>Which pest control services are available?</h3><p>Our core services include pest, termite, cockroach, bed bug, mosquito and rodent control, plus commercial, residential, fumigation and pre-construction termite treatment services.</p></article><article class="card"><h3>How can I request a quotation?</h3><p>Call ${phone}, email ${email}, or use the enquiry form on this website.</p></article></div>`;}
function serviceLinks(loc){return services.map(s=>`<li><a href="/services/${s.slug}/">${esc(s.name)}</a></li>`).join('');}
// homepage
write('index.html',layout('Pest Control & Termite Services | CSS Service Solution','CSS Service Solution provides pest control, termite control, cockroach, bed bug, mosquito, rodent, fumigation and related services across selected locations in North India.',site+'/',`<section class="hero"><div class="wrap"><div class="crumb">Home</div><h1>Professional Pest Control Services Across North India</h1><p>CSS Service Solution provides pest control and termite treatment solutions for residential and commercial properties, with location coverage across Uttar Pradesh, Bihar, Haryana, Rajasthan and Punjab.</p><div class="actions"><a class="btn" href="tel:${phone}">Call ${phone}</a><a class="btn secondary" href="https://wa.me/${wa}">WhatsApp Us</a><a class="btn" href="/contact/">Get a Quote</a></div></div></section><section class="section"><div class="wrap"><h2>Our Services</h2><div class="grid">${serviceCards()}</div></div></section><section class="section"><div class="wrap"><h2>Service Areas</h2><div class="grid">${states.map(st=>`<article class="card"><h3><a href="/${stateSlug[st]}/">${st}</a></h3><p>Explore CSS Service Solution locations and available services in ${st}.</p></article>`).join('')}</div></div></section><section class="section"><div class="wrap notice"><strong>Need a local pest control quotation?</strong><p>Tell us your city and required service. We'll help you identify the appropriate CSS Service Solution service option.</p><a class="btn" href="/contact/">Request a callback</a></div></section>`));
// services index
write('services/index.html',layout('Pest Control Services | CSS Service Solution','Explore pest control and termite treatment services offered by CSS Service Solution.',site+'/services/',`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / Services</div><h1>Our Pest Control Services</h1><p>Choose a service below to learn about the solution and find relevant service-area pages.</p><div class="grid">${serviceCards()}</div></div></section>`));
// service pages
for(const s of services){write(`services/${s.slug}/index.html`,layout(`${s.name} | CSS Service Solution`,`${s.desc} Contact CSS Service Solution at ${phone}.`,`${site}/services/${s.slug}/`,`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / <a href="/services/">Services</a> / ${esc(s.name)}</div><h1>${esc(s.name)}</h1><p>${esc(s.desc)}</p><h2>What this service is for</h2><p>CSS Service Solution can discuss the appropriate treatment approach based on the pest issue, property type, site conditions and service location. Treatment methods and service scope should be confirmed during enquiry.</p><h2>Find service coverage</h2><div class="grid">${locations.slice(0,60).map(l=>`<article class="card"><h3><a href="/${l.state_slug}/${l.slug}/">${esc(l.branch)}</a></h3><p>${esc(l.state)}</p></article>`).join('')}</div><div class="notice"><strong>Need a quotation?</strong><p>Call ${phone} or WhatsApp us with your city and property type.</p><div class="actions"><a class="btn" href="tel:${phone}">Call Now</a><a class="btn secondary" href="https://wa.me/${wa}">WhatsApp</a></div></div></div></section>`));}
// states and locations
for(const st of states){const list=locations.filter(l=>l.state===st); write(`${stateSlug[st]}/index.html`,layout(`Pest Control Services in ${st} | CSS Service Solution`,`Find CSS Service Solution pest control and termite service locations across ${st}.`,`${site}/${stateSlug[st]}/`,`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / ${esc(st)}</div><h1>CSS Service Solution Service Areas in ${esc(st)}</h1><p>Explore our listed locations and available pest control services in ${esc(st)}.</p><div class="grid">${locationCards(list)}</div></div></section>`));
 for(const l of list){
   const city=esc(l.branch); const canonical=`${site}/${l.state_slug}/${l.slug}/`;
   write(`${l.state_slug}/${l.slug}/index.html`,layout(`Pest Control Services in ${city} | CSS Service Solution`,`CSS Service Solution pest control and termite services in ${city}, ${st}. Call ${phone} for a quotation.`,canonical,`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / <a href="/${l.state_slug}/">${esc(st)}</a> / ${city}</div><h1>Pest Control Services in ${city}</h1><p>CSS Service Solution provides pest control and related services for residential and commercial property enquiries in ${city}, ${esc(st)}.</p><div class="notice"><strong>Local service information</strong><ul>${l.addresses.map(a=>`<li>${esc(a)}</li>`).join('')}</ul><p>Service availability should be confirmed before booking.</p></div><h2>Services</h2><ul>${serviceLinks(l)}</ul><h2>Why contact CSS Service Solution?</h2><ul><li>Multiple pest control service categories.</li><li>Residential and commercial service options.</li><li>Local enquiry and quotation support.</li></ul>${faq(l.branch)}<div class="actions"><a class="btn" href="tel:${phone}">Call ${phone}</a><a class="btn secondary" href="https://wa.me/${wa}?text=${encodeURIComponent('Hello CSS Service Solution, I need pest control service in '+l.branch+'.')}">WhatsApp</a></div></div></section>`));
 }
}
// contact, areas
write('contact/index.html',layout('Contact CSS Service Solution | Pest Control','Contact CSS Service Solution for pest control, termite treatment, fumigation and related service enquiries.',site+'/contact/',`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / Contact</div><h1>Contact CSS Service Solution</h1><p>Call, WhatsApp or email us with your city, service required and property type.</p><div class="actions"><a class="btn" href="tel:${phone}">Call ${phone}</a><a class="btn secondary" href="https://wa.me/${wa}">WhatsApp</a><a class="btn" href="mailto:${email}">Email Us</a></div><h2>Send an enquiry</h2><form class="form" action="mailto:${email}" method="post" enctype="text/plain"><input name="Name" placeholder="Your name" required><input name="Mobile" placeholder="Mobile number" required><input name="City" placeholder="City"><select name="Service"><option>Select service</option>${services.map(s=>`<option>${esc(s.name)}</option>`).join('')}</select><textarea name="Message" placeholder="Tell us about your pest issue or property"></textarea><button class="btn" type="submit">Send Enquiry</button></form><p><strong>Email:</strong> ${email}</p><p><strong>Coverage:</strong> Uttar Pradesh, Bihar, Haryana, Rajasthan and Punjab.</p></div></section>`));
write('service-areas/index.html',layout('Service Areas | CSS Service Solution','Explore CSS Service Solution pest control service locations across Uttar Pradesh, Bihar, Haryana, Rajasthan and Punjab.',site+'/service-areas/',`<section class="section"><div class="wrap"><div class="crumb"><a href="/">Home</a> / Service Areas</div><h1>Service Areas</h1><p>Browse our listed CSS Service Solution locations.</p><div class="grid">${states.map(st=>`<article class="card"><h3><a href="/${stateSlug[st]}/">${st}</a></h3><p>${locations.filter(l=>l.state===st).length} listed location records.</p></article>`).join('')}</div></div></section>`));
write('robots.txt','User-agent: *\nAllow: /\nSitemap: '+site+'/sitemap.xml\n');
let urls=['/','/services/','/contact/','/service-areas/'];
for(const st of states){urls.push('/'+stateSlug[st]+'/'); for(const l of locations.filter(x=>x.state===st)){urls.push('/'+l.state_slug+'/'+l.slug+'/');}}
for(const s of services) urls.push('/services/'+s.slug+'/');
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+[...new Set(urls)].map(u=>'<url><loc>'+site+u+'</loc></url>').join('')+'</urlset>');
console.log(`Built ${locations.length} unique location pages plus ${services.length} service pages.`);